version: '3.4'

services:
  redis:
    image: 'redis:alpine'
    container_name: redis
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

  authentication:
    container_name: authentication
    build: ./
    ports:
      - '8000:8000'
    restart: always

  auth_db:
    image: postgres:latest
    container_name: auth_db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PORT: 5432
    ports:
      - "6432:5432"
    volumes:
      - authdata:/var/lib/postgresql/data

volumes:
  redis-data:
  authdata:
